<<<<<<< HEAD
# Generated by Django 2.0.1 on 2018-01-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_auto_20180127_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='crop_range',
            new_name='_range',
        ),
    ]
=======
# Generated by Django 2.0.1 on 2018-01-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_auto_20180127_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='crop_range',
            new_name='_range',
        ),
    ]
>>>>>>> e854a0e1d078f16e921a24a3e201c203befc9c4a
